version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - VK_APP_ID=${VK_APP_ID:-54556179}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET:-488uLwXVh0NbUFcrJIvA}
      - VK_SERVICE_KEY=${VK_SERVICE_KEY:-a5b5b6aaa5b5b6aaa5b5b6aa3ca68ae59aaa5b5a5b5b6aacc52bb65014d8826cb301184}
      - DATABASE_URL=${DATABASE_URL:-}
      - PORT=80
      - VK_SERVICE_PORT=5000
      - VK_SERVICE_URL=http://localhost:5000
    restart: unless-stopped
